micronaut:
  application:
    name: mn-auto-ts

dataSource:
  dbCreate: create
  url: jdbc:h2:file:./devDb
#  url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
# Comment out dataSources to restore functionality
dataSources:
  altDataSource:
    dbCreate: create
    url: jdbc:h2:file:./altDevDb
#    url: jdbc:h2:mem:altDevDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
hibernate:
#  hbm2ddl:
#    auto: none
  show_sql: false
#  cache:
#    queries: false
#    use_second_level_cache: false
#    use_query_cache: false
